### ISSUE TITLE
warning: munmap failed: Invalid argument

### ISSUE THREAD

**Issue by flatsiedatsie** [ngxson/wllama#7] opened 2024-04-28 13:13 UTC
I'm seeing this warning when loading a model:

```
............................................................................................warning: munmap failed: Invalid argument
```

Is it anything to worry about?

**Comment by ngxson** [comment] 2024-04-29 20:41
That seems like a problem with mmap support in emscripten. I'm not sure where the problem comes from, probably I should see if there's a related issue in emscripten's repo: https://github.com/emscripten-core/emscripten/issues?q=munmap

In the meantime, could you please give more details on the model and configs that you're using?

**Comment by flatsiedatsie** [comment] 2024-04-30 15:46
I'm using many models, but in this case it's https://huggingface.co/bartowski/h2o-danube2-1.8b-chat-GGUF/resolve/main/h2o-danube2-1.8b-chat-Q5_0.gguf with default settings.

**Comment by flatsiedatsie** [comment] 2024-05-04 16:08
I believe this happens with every model I load.

**Comment by felladrin** [comment] 2024-05-09 15:09
I also get this warning for any model I use.

It's also reproducible in the [demo](https://ngxson.github.io/wllama/examples/basic/):
<img width="1429" alt="image" src="https://github.com/ngxson/wllama/assets/418083/499fba9f-a5d5-4e2b-b48c-e94b0f26a012">

**Comment by flatsiedatsie** [comment] 2024-05-11 10:52
Perhaps this is of interest, I came accross it by accident:

https://github.com/xenova/transformers.js/pull/545/files/0f58121096f1cf73e0b04b01d7c2a4e426a7822a..a4d88acdfadec970095734ef85f2879c521ef060

**Comment by ngxson** [comment] 2024-05-18 14:28
I'm closing this issue because this error message is not very important (can be ignored)

Technical explanation: llama.cpp uses `mmap()` to read files, which may use less memory than traditional `read()` syscall. This benefits us because wllama also use `mmap()` to prevent copying files (see #39). However, we don't implement `munmap()` because we don't need to unload file. This is not needed because to unload a model, we can simply call `wllama.exit()`

**Closed by ngxson** 2024-05-18 14:28 UTC
